database_config:
  dbms: sqlite
  db: sqless.db

schema:
  users:
    tablename: user
    fields:
      id: integer
      username: char
      email: char
      failed_logins: integer
  posts:
    tablename: post
    fields:
      id: integer
      user: integer
      title: char
      content: text
