name: Robot Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with robot
      run: |
        export PYTHONPATH="${PYTHONPATH}:./src/"
        cat tests/config/sqlite.yml > tests/config/db_config.yml
        python utils/build_test_db.py sqlite
        robot --outputdir tests/reports/ tests
    - uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: tests/reports
